events {
    worker_connections 1024;
}

http {
    server {
        listen 8080;

        # 1. Endpoint / -> Backend API info
        location / {
            proxy_pass http://api:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 2. Endpoint /health -> Backend Health Check
        location /health {
            proxy_pass http://api:3000/health;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 3. Endpoint /api/products -> Backend Products API
        location /api/products {
            proxy_pass http://api:3000/api/products;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}